CREATE TABLE "expenses" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Category"	TEXT NOT NULL,
	"Value"	REAL NOT NULL,
	"Date"	TEXT NOT NULL,
	"Created"	TEXT NOT NULL,
	"Updated"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
)